### ISSUE TITLE
Does this still work on win 11?

### ISSUE THREAD

**Issue by UltimateBoi** [GameTec-live/msfamdisable#11]
![image](https://user-images.githubusercontent.com/63293118/148575135-bbd839e4-d0c0-409a-9ad5-c11a4c82baa0.png)
keep getting error code 1

**Comment by UltimateBoi** [comment]
it also still shows this 
![image](https://user-images.githubusercontent.com/63293118/148575973-75961ee9-02dd-4b7e-b45a-e30b9aa47962.png)

**Comment by GameTec-live** [comment]
ok, its broken... honestly i stopped developing on this... maybe some day ill do a rewrite.... but have u executed this with admin perms?

**Comment by UltimateBoi** [comment]
yes and also please do rewrite lol

**Comment by GameTec-live** [comment]
maybe try renameing the files manually... they are located in C:\Windows\System32...

**Comment by UltimateBoi** [comment]
? which files?

**Comment by UltimateBoi** [comment]
just tell me how to do it manually please

**Comment by GameTec-live** [comment]
The wpcmon.exe and wpctok.exe in system32

**Comment by GameTec-live** [comment]
Ill do a rewrite amnext weekend, after my exam... ill declare this issue closed...

**Comment by UltimateBoi** [comment]
> The wpcmon.exe and wpctok.exe in system32

rename to what?

**Comment by GameTec-live** [comment]
> > The wpcmon.exe and wpctok.exe in system32
> 
> rename to what?
> 

To amything thats not the original filename

**Comment by UltimateBoi** [comment]
It says i cant

**Comment by GameTec-live** [comment]
but if ur bio is correct, download the sourcecode and take a look at what to do...

**Comment by UltimateBoi** [comment]
it said i can do python but im mainly into javascript and java. i can try though

**Comment by UltimateBoi** [comment]
pog

**Comment by GameTec-live** [comment]
Im sorry, that i maybe offended u... but im only 1 person who has some exams in school... i wrote this an eternety ago where win 11 didnt exist and i thought it would still work on win 11, but as u showed me it doesnt and there is demand for it... so ill prob do a rewrite this weekend

**Comment by UltimateBoi** [comment]
nono its ok i compleately understand that you have exams and you wrote ageees ago. I have many programs that are the same and are mostly broken and cant update them because i have long homeworks. Its fine, just do it whenever you can get round to it!

**Comment by GameTec-live** [comment]
Im sorry... with win 11 ive reached the limit of my python / windows skills... ive updated the readme corosponding

**Comment by GameTec-live** [comment]
a fork is welcome...

**Comment by GameTec-live** [comment]
if ud like to cooperate with me on v2, here is my discord: GameTec_live#2350

**Comment by UltimateBoi** [comment]
cool
