### ISSUE TITLE
User information help.

### ISSUE THREAD

**Issue by Gamecat178** [GameTec-live/msfamdisable#12]
Having trouble figuring out how on what to put for the Organization

**Comment by GameTec-live** [comment]
What does this mean?

**Comment by Gamecat178** [comment]
where can you find the information needed to put in the fields and etc. it was not to clear and I got stuck on it.

**Comment by Gamecat178** [comment]
I have the exe file if that helps.

**Comment by GameTec-live** [comment]
if its windows 11, im sorry...  it doesnt work as described in issue 11 https://github.com/GameTec-live/msfamdisable/issues/11

**Comment by GameTec-live** [comment]
due to my laptop haveing issues at the time of createing the version 18 installer, i lost the serial keys.... pls use version 17 (same without the installer) https://github.com/GameTec-live/msfamdisable/releases/tag/17
