### ISSUE TITLE
I cannot press next

### ISSUE THREAD

**Issue by TommyB2006** [GameTec-live/msfamdisable#13]
![image](https://user-images.githubusercontent.com/65030554/175698301-bafa6393-8376-41ac-8077-c0666cc56b38.png)

**Comment by GameTec-live** [comment]
seeing, that you are on windows 10, ig i still have to give support...

**Comment by GameTec-live** [comment]
use the zip release, ive lost the file with my license keys.... sry!
https://github.com/GameTec-live/msfamdisable/releases/tag/17
