### ISSUE TITLE
Git is installed but does not seem to be detected

### ISSUE THREAD

**Issue by byzocker** [GameTec-live/msfamdisable#3]
![image](https://user-images.githubusercontent.com/59401089/115115973-85498c80-9f97-11eb-93e5-409260b14e8b.png)

**Comment by GameTec-live** [comment]
Will fix it shortly

**Comment by GameTec-live** [comment]
What happens, if you ignore the error? Try executing Updater.py in the files folder... Does it throw an error? If it doesnt, dont forget to delete the Update folder... Thanks!

**Comment by GameTec-live** [comment]
Bugs fixed!
