### ISSUE TITLE
Searching for Programmers / Contributors /Mods

### ISSUE THREAD

**Issue by GameTec-live** [GameTec-live/msfamdisable#4]
Searching for Programmers / Contributors /Mods
If you know a bit of python and want to help me, email me:
benedikt.werner08@gmail.com
(German/English)

**Comment by byzocker** [comment]
idk

**Comment by 404LikesU** [comment]
Hi Guys

**Comment by GameTec-live** [comment]
> Hi Guys

Hi! If you wanna help me, then maybe mail me?
