### ISSUE TITLE
files

### ISSUE THREAD

**Issue by MineIsYours007** [GameTec-live/msfamdisable#5]
So iam 17 years old and i have this family safety on my laptop... 
I want to play minecraft lol but my parents installed family safety on my pc and now i can't  play anymore.
I saw your files but i don't know what i need to do with it.
if you can help me pls it would be great!
and maybe a good hing to know is that iam not the admin or operator on my pc.

so rn I downloaded the latest release and installed the git-installer but when i tried to install the installer.bat and the python-install I got a notification that iam not the admin on my laptop and i can't install it...

if you want to send me messages here is my discord.
MineIsYours007#5462

**Comment by GameTec-live** [comment]
Contact you over discord!
