### ISSUE TITLE
"An minor error occured! Errorcode: 1"

### ISSUE THREAD

**Issue by dantopps04** [GameTec-live/msfamdisable#7]
![image](https://user-images.githubusercontent.com/85835639/121811519-97287280-cc5c-11eb-977c-e97c21bcd2e1.png)
got this when pressing disable

**Comment by GameTec-live** [comment]
Hmm... windows and python3 version?

**Comment by GameTec-live** [comment]
Oh by the way! Sorry for the late reply...

**Comment by GameTec-live** [comment]
No reply and maybe just a anomally
