### ISSUE TITLE
Still receiving notis when installing from Microsoft Store

### ISSUE THREAD

**Issue by royalhope** [GameTec-live/msfamdisable#9]
When I'm installing an app from Microsoft Store, the phone notifs are still coming. Any solutions?

**Comment by GameTec-live** [comment]
Wich phone notifications? And maybe you cpuld just dont use the msstore, like so many others?

**Comment by royalhope** [comment]
I use ms store because it has safe apps and many apps or only available from there

**Comment by GameTec-live** [comment]
Maby sing out of ms store and sign in with another account

**Comment by royalhope** [comment]
I'll try that.
